### ISSUE TITLE
embed

### ISSUE THREAD

**Issue by gedw99** [hack-pad/hackpadfs#17]
I think it would be cool if the https://pkg.go.dev/embed package was supported.

Tinygo just got support for EMbed as well as generics https://github.com/tinygo-org/tinygo/releases/tag/v0.24.0

**Comment by JohnStarich** [comment]
Hey @gedw99. What did you have in mind for hackpadfs support? It looks like embed is already interoperable with the built-in `io/fs` package, so it works with hackpadfs out of the box. 👍

**Comment by gedw99** [comment]
Ah it’s API compatible ? Will try embed out then. Thanks @JohnStarich 

I wanted to use this as a test tool: 
https://github.com/twpayne/go-vfs

there is a compatible layer here for Adern btw:
https://github.com/twpayne/go-vfsafero

then I want to try to get go-git working: https://github.com/go-git/go-git

Running a git server with only go-get using binary patches works today so there is no logical reason that a git client can work.

**Comment by JohnStarich** [comment]
Yep, fully compatible with the standard library just like hackpadfs. I'll go ahead and close – feel free to continue the conversation!

Those libraries are interesting, although they take a "large interface" approach.
I've found that style is not easy to work with.<sup>[[1]](https://github.com/hack-pad/hackpadfs/issues/12)[[2]](https://johnstarich.medium.com/write-once-store-anywhere-extensible-file-systems-for-go-65c7c0949e74?source=rss-55e402a0ee1a------2)</sup>
