### ISSUE TITLE
is hackpad/os writable?

### ISSUE THREAD

**Issue by jritsema** [hack-pad/hackpadfs#29]
Hey there.  Really cool project!  Just trying this out and using a `mem.NewFS()` in a test works great.  When I swap out my implementation with a `os.NewFS()`, I'm getting the following error.

```
mkdir out: read-only file system
```

My understanding was that `os` was writable.  Is that incorrect?

For context, I'm writing a scaffolding tool that creates a bunch of directories and files.  I'm looking for a library that can encapsulate the directory structure I'm creating and ease testing.

**Comment by JohnStarich** [comment]
Hey @jritsema, I'm glad you like it!

Yep, `*os.FS` is indeed writable. I think you're in the right place. Could you maybe share a small example that fails for you?

Also, can you share which file paths you're accessing on the `*os.FS` as well as which operating system you're using?

**Comment by jritsema** [comment]
I've got this resolved.  I was inadvertently calling `Sub()` with a relative path.

BTW, it does seem like the example on the README.md needs updating (at least for go 1.19). Seems like I had to remove the trailing `/` from the working directory.

```go
package main

import (
	goOS "os"
	"path"

	"github.com/hack-pad/hackpadfs"
	"github.com/hack-pad/hackpadfs/os"
)

func main() {

	osfs := os.NewFS()
	workingDirectory, _ := goOS.Getwd()
	fs, err := osfs.Sub(workingDirectory[1:])
	if err != nil {
		panic(err)
	}

	dir := "foo/bar"
	err = hackpadfs.MkdirAll(fs, dir, hackpadfs.FileMode.Perm(0755))
	if err != nil {
		panic(err)
	}
	file, err := hackpadfs.Create(fs, path.Join(dir, "hello.txt"))
	if err != nil {
		panic(err)
	}
	_, err = hackpadfs.WriteFile(file, []byte("world"))
	if err != nil {
		panic(err)
	}

}

```

**Comment by JohnStarich** [comment]
Oops, you're right! That example is now fixed: https://github.com/hack-pad/hackpadfs/pull/30

**Comment by jritsema** [comment]
Hi @JohnStarich.  I just open sourced a small library (used to build another tool I'm working on) based on hackpadfs, in case others find it useful.

https://github.com/jritsema/scaffolder

**Comment by JohnStarich** [comment]
Oh cool! Thanks for sharing the FS love ❤️
