### ISSUE TITLE
Potential dependency inconsistency

### ISSUE THREAD

**Issue by Ben131-Go** [hack-pad/hackpadfs#32]
## Dependency line:
github.com/hack-pad/hackpadfs/examples --> [github.com/minio/minio](https://github.com/hack-pad/hackpadfs/blob/main/examples/go.mod#L7) --> [github.com/gomodule/redigo](https://github.com/hack-pad/hackpadfs/blob/main/examples/go.mod#L76) <br>
github.com/minio/minio 9ca25bd --> github.com/gomodule/redigo v1.8.5<br>
<https://github.com/minio/minio/blob/9ca25bd48f7fec228f246ef5452465be009d4d7a/go.mod#L234>

## Background
Repo `github.com/minio/minio` at version `9ca25bd` uses replace directive to pin dependency `github.com/gomodule/redigo` to version `v1.8.5`.<br>
According to [Go Modules wikis](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive), `replace` directives in modules other than the `main module` are ignored when building the main module.
It means such replace usage in dependency's go.mod cannot be inherited when building main module. And it turns out that `github.com/hack-pad/hackpadfs/examples` indirectly relies on `gomodule/redigo@v2.0.0`, which is different from the pinned version `minio/minio` needed.<br>
><https://github.com/hack-pad/hackpadfs/blob/main/examples/go.mod>(Line 76)
```Go
github.com/gomodule/redigo v2.0.0+incompatible // indirect
```

><https://github.com/minio/minio/blob/9ca25bd48f7fec228f246ef5452465be009d4d7a/go.mod>(line 32&234)
```Go
github.com/gomodule/redigo v2.0.0+incompatible
replace github.com/gomodule/redigo => github.com/gomodule/redigo v1.8.5
```
So this is just a reminder in the hope that you can notice such an inconsistency.
### 1. Bump the version of dependency `github.com/minio/minio`
You may try upgrading dependency `github.com/minio/minio` to a newer version, which may have eliminated the use of this directive.

### 2. Add the same replace rule to your go.mod
```Go
replace github.com/gomodule/redigo => github.com/gomodule/redigo v1.8.5
```

**Comment by JohnStarich** [comment]
Hey @Ben131-Go, thanks for opening. We can upgrade the minio dependencies, of course. I've opened a PR to do so [here](https://github.com/hack-pad/hackpadfs/pull/33).

Please be aware that the examples aren't intended to be imported or have any sort of back-compatibility guarantees – they only function as copyable working examples. Feel to contribute an upgrade, too ❤️
